services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./epytodo.sql:/docker-entrypoint-initdb.d/epytodo.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  api:
    build: ./
    ports:
      - "${PORT}:${PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: db
      PORT: ${PORT}
      DB_PORT:
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  db-data: